### ISSUE TITLE
Uptime Kuma

### ISSUE THREAD

**Issue by marktopper** [easypanel-io/templates#43]
https://github.com/louislam/uptime-kuma

**Comment by Ponkhy** [comment]
Uptime Kuma is already on my list and have tried to implement a template. Unfortunately there is a WebSocket issue in combination with Easypanel right now, but soon as it's resolved i will write a template for it.

**Comment by marktopper** [comment]
@Ponkhy any chance you can share your current progress. Maybe I would be able to help solve this WebSocket issue?

**Comment by Ponkhy** [comment]
> @Ponkhy any chance you can share your current progress. Maybe I would be able to help solve this WebSocket issue?

I just looked and didn't find it on my PC anymore, but shouldn't be to hard to make a new one.
