### ISSUE TITLE
[Bug]: Create From Schema not working for schema json with the git source

### ISSUE THREAD

**Issue by IvanRublev** [easypanel-io/templates#458]
Version: Easypanel 1.23.2

**What's now:**

When I try to create an app from the schema with at least one source pointing to the ssh git repo, the app is not created instead I get error message: `Unexpected Error
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bservices%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

Steps to reproduce:

Use the attached file [bug-schema.txt](https://github.com/easypanel-io/templates/files/12700031/bug-schema.txt) or do the following.

* create new "bug-create-from-template" project in easypanel 
* crate service - app "app_from_docker"
* for source, select Git and press Generate SSH Key
* add  generated key to git system (I use Gitea)
* add the path to ssh git repo ssh://git@host:port/path_to_repo, set branch to master, path to / and Save
* go to project settings and copy the project schema
* remove the app from the project
* go to project templates and create an app from the schema copied before by clicking Create From Schema
* app is not created, error message described above appears

**Expected:**

* app is created

**Comment by RobertofLocksley** [comment]
Interestingly enough, I had the exact same error when creating from template schema: 
[bug-schema.txt](https://github.com/easypanel-io/templates/files/12704036/bug-schema.txt)
I later realized that if I changed the the project name to lowercase, e.g. "Directus" to "directus", the schema worked flawlessly.
I'm guessing that this is a fairly general error code that will be thrown if anything unexpected occurs? (although I'm no expert)
All the same, I'm not at all positive that this is related...

**Comment by Supernova3339** [comment]
the project name is autofilled in easypanel

**Comment by IvanRublev** [comment]
> I later realized that if I changed the the project name to lowercase, e.g. "Directus" to "directus", the schema worked flawlessly. I'm guessing that this is a fairly general error code that will be thrown if anything unexpected occurs? (although I'm no expert) All the same, I'm not at all positive that this is related...

Thanks for sharing, it might feel annoying when you can't give the case you want to labels you add 🙂 Of course more specific indication of the error's cause might be helpful to reduce the search time.

Even though I haven't found the combination to make the ssh repo filled from the schema with Create From Schema button so this issue is about this specific use case.

**Comment by IvanRublev** [comment]
Moved to https://feedback.easypanel.io/bug-reports/p/create-from-schema-not-working-for-schema-json-with-the-git-source
