### ISSUE TITLE
ChatWoot Template seems to have a problem

### ISSUE THREAD

**Issue by michaelvips** [easypanel-io/templates#520]
Some things like send a message works well but I am with a error on images and files, something about rails.
500 (Internal Server Error) 

![image](https://github.com/easypanel-io/templates/assets/21130174/6ccad4b7-7c9b-4eb3-b833-8ec9233f927c)

**Comment by michaelvips** [comment]
I solve this using this command after app online  bundle exec sidekiq -C config/sidekiq.yml how to put this in the template ?

**Comment by deiucanta** [comment]
https://github.com/easypanel-io/templates/blob/main/templates/chatwoot/index.ts#L81

It seems it's already there

**Comment by michaelvips** [comment]
Olá @deiucanta sim existe, mas com todos os serviços iniciados, é necessário executar manualmente o comando dentro do aplicativo chatwoot
