### ISSUE TITLE
Chatwoot Templates Sidekiq Image

### ISSUE THREAD

**Issue by cwmkthubconnect** [easypanel-io/templates#549]
Hello Easypanel team, we would first like to thank you for your immense work on behalf of our community

We noticed a problem in the variable

FRONTEND_URL=https://$(PRIMARY_DOMAIN)

So Sidekiq doesn't read it, and it doesn't record images

**Comment by luiis716** [comment]
what is happening and what whenever it puts 

FRONTEND_URL=https://$(PRIMARY_DOMAIN)

with https:// it duplicates and when sent image via api box it goes https://https://mydomain.com


duplicating the https and the solution I found was just FRONTEND_URL=$(PRIMARY_DOMAIN)

It would be more viable to just leave the variable without the http
